[lint]
select = ["E", "F", "I", "B"]  # Основные группы правил
ignore = ["E501"]              # Игнорировать длину строк

[format]
indent-style = "space"         # Использовать пробелы для отступов
quote-style = "single"         # Одинарные кавычки

[lint.isort]
known-first-party = ["hexlet_components"]  # Локальные модули
