[lint]
select = ["E", "F", "I", "B"]
ignore = ["E501"]

[lint.isort]
known-first-party = ["hexlet_components"]

[format]
# Для этой версии используйте:
indent-style = "space"  # или "tab"
quote-style = "single"
